### ISSUE TITLE
Update SGX SDK to version 2.5

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-secure-chaincode#28]
New SGX SDK v2.5 for Linux has been released recently. We should upgrade and test.

**Comment by g2flyer** [comment]
As discussed elsewhere, we should move to our own docker.  My proposal would be to go directly to a DCAP based one (which stills supports EPID), so i propose we cover SDK update to the same effort. I don't think there is any urgent need to 2.5 otherwise (except that maybe pull request #29  can be easier fixed by going to 2.5 instead of freezing the docker-sgx commit) ..?

**Comment by mbrandenburger** [comment]
we fixed #29 using a quick fix. I agree that updating to v2.5 can wait.

**Comment by bvavala** [comment]
close - solved
